### ISSUE TITLE
Add 'SecurityScheme' fragment type to the table

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#1]

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/362

**Comment by sichvoge** [comment]
That shouldn't be part of the parser, right @petrochenko-pavel-a

**Comment by petrochenko-pavel-a** [comment]
We should check that this fragment name is actually supported (definition system type is named differently so an alias is actually used), checking

**Comment by petrochenko-pavel-a** [comment]
Yep, it works
