### ISSUE TITLE
Add more clarifications and examples on how type instances get validated

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#17]
RC1 spec does not specifies any rules for validation of type instances. RC2 should add more examples of instance validation as well as the rules associated with each facet. These rules will make clear what one should expect from a processor output.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/315

**Comment by petrochenko-pavel-a** [comment]
There is no parser work required.
