### ISSUE TITLE
Clarify that `schema` and `type` are mutually exclusive

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#22]
RAML 1.0 RC2 should clearly state that `schema` and `type` are mutually exclusive. Therefore, the following should be invalid in any future version of RAML.

``` yaml
/resource:
  get:
    responses: 
      200:
        body: 
          application/json:
            schema: 
            type:
```

You are still allowed to have global definitions for `schemas` or `types`, although it is recommended to use `types` only.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/308

**Comment by sichvoge** [comment]
Not yet done and related to #69
