### ISSUE TITLE
Remove `allowMultiple` from annotation types

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#31]
According to the YAML spec, multiple keys with the same name are not allowed. RAML should also comply to that and therefore the spec should not allow to define annotations multiple times to the same node. Hence remove the property `allowMultiple` from the annotation type node.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/288

**Comment by petrochenko-pavel-a** [comment]
Already implemented
