### ISSUE TITLE
Remove `parameters` from the available nodes inside a resource type or trait node

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#32]
![image](https://cloud.githubusercontent.com/assets/498114/13669663/d9139e30-e6bc-11e5-90df-5dcd03993d7a.png)

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/287

**Comment by petrochenko-pavel-a** [comment]
This is done long time ago.
