### ISSUE TITLE
Improve annotation target table

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#34]
Currently, names and description inside the annotation table are not very clear. Let's improve them.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/283

**Comment by sichvoge** [comment]
Only think to do here is that the current target table in the spec reflects the definition system.

**Comment by petrochenko-pavel-a** [comment]
yep.
