### ISSUE TITLE
Facets are part of any type (object, array, or scalar)

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#4]
Currently the RC1 spec has an additional property called `facets` that adds user defined restrictions to scalar types. Actually these restrictions can be applied to any other type (object, scalar, or array) except file. That needs to be  more clear in RC2.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/347

**Comment by petrochenko-pavel-a** [comment]
This is implemented already both inworkbench and parser
