### ISSUE TITLE
Add displayName to a specific declaration of `securitySchemes`; and remove `description` and `displayName` in `describedBy`

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#44]
In RAML 1.0 RC, the `describedBy` property of a security scheme has two additional properties `description` and `displayName`. My question is if we really need them to be there? A specific security scheme already has a `description` property and, IMHO, that makes the one in `describedBy` redundant. I also would understand if we move `displayName` up to the security scheme property as well, but it should not be in `describedBy`.

Happy to hear other opinions.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/244

**Comment by petrochenko-pavel-a** [comment]
This is fixed during definition system cleanup
