### ISSUE TITLE
Remove `displayName` on API root level

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#50]
Reading through the RAML 1.0 spec and comparing that to the previous version I wonder why RAML 1.0 allows to have `displayName` on the API root level now? I believe in 0.8 its been only used to give a "friendly" name to resources, but I don't understand why we should do the same on the API root level since we have `title` already.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/222

**Comment by petrochenko-pavel-a** [comment]
This is handled by definition system cleanup
