### ISSUE TITLE
Are you allowed to pull in libraries in global definitions such as traits and resource types?

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#6]
Currently, the RC1 spec allows to define `uses` and therefore bringing in libraries inline. Are we really gonna allow that? If yes, why do would we allow that?

![image](https://cloud.githubusercontent.com/assets/498114/14138655/639f51a8-f666-11e5-9da5-9a07ab4f1750.png)

IMHO, that should not be allowed since I don't really see any use cases to do that on any global declaration.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/341

**Comment by petrochenko-pavel-a** [comment]
This is covered by uses behaviour change.
