### ISSUE TITLE
It looks like Overloading section is missing

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#60]
We had a draft of language clarifying how overloading should work, but we do not have an overloading section here: http://docs.raml.org/specs/1.0/

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/199

**Comment by petrochenko-pavel-a** [comment]
This is not relevant any more
