### ISSUE TITLE
Support "uses" in Typed Fragments

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#63]
Typed fragments should boost **Modularization** significantly, yet their still not powerful enough.

For example, an API with a lot of **Types** should be able to create a **DataType** fragment file per type, this is a major improvement in terms of project maintainability & scalability, especially in teams where developers do the docs.
RAML 1.0 allows that but each file is isolated from the world, it has no reference to anything.

If one would like to use Typed fragments, it will have to make every type as a fragment, even custom types... using libraries is not an option.

The **DataType** typed fragment should support "uses" so the fragment could get some context.

It should also be considered to allow a fragment to call "uses" to library that is the "parent" of that fragment, a recursion detector should be implemented. This is not crucial as "family members" of the same library can reference each other directly, if needed.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/195

**Comment by petrochenko-pavel-a** [comment]
This is addressed by #48 closing
