### ISSUE TITLE
Override Rules

### ISSUE THREAD

**Issue by VasiliyLysokobylko** [petrochenko-pavel-a/raml-js-parser2-issues#65]
Certain behaviors were not explicit in RAML 0.8; this fixes them. This includes:
- Peer resources that resolve to the same path, e.g. `/users` with a sub-resource `/{id}`, alongside `/users/{id}`
- Peer resources with similar URI parameters, e.g. `/{pictureId}` and `/{videoId}`
- Duplicate methods on a resource
- Multiple occurrences of the same media type in a response
- The order in which to apply multiple traits (and now types, since there is multiple inheritance)

There are a few others to clarify too.

**Comment by VasiliyLysokobylko** [comment]
https://github.com/raml-org/raml-spec/issues/184

**Comment by sichvoge** [comment]
That one has been submitted as a PR already. Since YAML does not allow multiple keys to be specified, the whole topic gets almost obsolete except for resources. See https://github.com/raml-org/raml-spec/pull/368

**Comment by petrochenko-pavel-a** [comment]
This is already implemented
